flaskypost/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskypost/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskypost import db
from flaskypost.models import Post
from flaskypost.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route('/post/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Successfully!', 'success')
        return redirect(url_for('main.index'))
    return render_template('newPost.html', form=form, legend='Create Post')


@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Successfully!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('newPost.html', form=form, legend='Post Update')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Successfully!', 'success')
    return redirect(url_for('main.index'))

flaskypost/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskypost import db, bcrypt
from flaskypost.models import User, Post
from flaskypost.users.forms import (RegistrationForm, LoginForm, UpdateProfileForm,
                                    RequestResetForm, ResetPasswordForm)
from flaskypost.users.utils import save_image_for_user, send_token_by_email

users = Blueprint('users', __name__)


@users.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    if form.validate_on_submit():
        if form.image.data:
            _img = save_image_for_user(form.image.data)
            current_user.image = _img
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Successfully!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_images/' + current_user.image)
    return render_template('profile.html', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=9)
    return render_template('user_page.html', posts=posts, user=user)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Wrong email or password.', 'danger')
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/password_reset', methods=['GET', 'POST'])
def password_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_token_by_email(user)
        flash('Please, check your email. If you do not see any messages, then check the folder "Spam"', 'success')
        return redirect(url_for('users.login'))
    return render_template('resetPassword.html', form=form)


@users.route('/password_reset/<token>', methods=['GET', 'POST'])
def password_reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Time expired or you do not have the access.', 'warning')
        return redirect(url_for('users.password_reset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('password_reset_token.html', form=form)

flaskypost/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlaskyPOST</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="shortcut icon" href="">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>
<body style="background-color: #434C53; margin: 15px;">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-2" href="{{ url_for('main.index') }}">Flasky<span style="color: #FFC118;">POST</span></a>
          {% if current_user.is_authenticated == False%}
            <small class="alert-message">Log In to access more features!</small>
          {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- <a class="nav-item nav-link" href="/">Home</a> -->
            </div>
            <!-- Navbar Right Side aka. log-side -->
            <div class="navbar-nav">
            {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.profile') }}" style="color: #FFC118;">PROFILE</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}" style="color: #FFF;">POST</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}" style="color: #FFF;">LOG OUT</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}" style="color: #FFF;">LOG IN</a>
                <a class="nav-item nav-link" href="{{ url_for('users.signup') }}" style="color: #FFC118;">SIGN UP</a>
            {% endif %}
                <a class="text-info ml-3 p-1" target="_blank" href="https://github.com/RuslanPr0g/FlaskyPOST" style="color: #fff;">GITHUB</a>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %} 
        {% endif %}
      {% endwith %}
      {% block body %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

flaskypost/templates/index.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="d-flex justify-content-start text-light mb-4">Total posts found: {{ posts.total }}</div>
{% if current_user.is_authenticated %}
    <!--User Login-->
    {% for post in posts.items %}
    <div class="post d-flex flex-column justify-content-between">
        <div class="post-header">
        - {{ post.date_posted.date() }} | {{ post.date_posted.strftime("%H") }}:{{ post.date_posted.strftime("%M") }}
        </div>
        <div class="post-content">
            <h1 class="display-4 mb-4" style="text-align: center;"><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title" style="color: black;">{{ post.title[0:60] }}</a></h1>
            <p class="text-secondary" style="text-align: center; font-size: 20px;">Posted by <a class="text-secondary font-weight-bold" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a></p>
            <hr>
            <p style="text-align: center;" class="post-content-p">{{ post.content[0:33] }}...</p>
        </div>
    </div>
    {% endfor %}
    <div class="page-nums d-flex justify-content-center" style="width: 330px; margin: auto;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-outline-secondary mb-4 ml-1" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-secondary mb-4 ml-1" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                <p class="btn ml-1" style="color: #fff;">...</p>
            {% endif %}
        {% endfor %}
    </div>


    <!--User Logout-->
    {% else %}
    {% for post in posts.items[0:5] %}
    <div class="post d-flex flex-column justify-content-between">
        <div class="post-header">
        - {{ post.date_posted.date() }}
        </div>
        <div class="post-content">
            <h1 class="display-4 mb-4" style="text-align: center;">{{ post.title[0:60] }}</h1>
            <p class="text-secondary" style="text-align: center; font-size: 20px;">Posted by <a class="text-secondary font-weight-bold" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a></p>
            <hr>
            <p style="text-align: center;" class="post-content-p">{{ post.content[0:33] }}...</p>
        </div>
    </div>
    {% endfor %}
    <div class="d-flex justify-content-center mt-4"><a href="{{ url_for('users.signup') }}" class="btn btn-success btn-lg">Sign UP</a> <span class="text-light ml-2" style="font-size: 30px;">to see more!</span></div>
{% endif %}
{% endblock %}

flaskypost/templates/login.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="signup d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" style="width: 500px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">Log In</legend>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.email(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            
            {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.password(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-check">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-label") }}
        </div>

        <small class="text-muted ml-3">
            <a href="{{ url_for('users.password_reset') }}" style="color: rgb(213,161,6);">Help, I've Forgot My Password</a>
        </small>
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
<div style="width: 550px; margin: auto;">
    <small class="text-muted">
       <span style="color: #FFF;">Have No Account?</span> <a href="{{ url_for('users.signup') }}" class="ml-2" style="color: #FFC118;">Sign Up</a> 
    </small>
</div>
{% endblock %}

flaskypost/templates/newPost.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="signup d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" class="mr-4" style="width: 500px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">{{ legend }}</legend>
        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            
            {% if form.title.errors %}
                {{ form.title(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.title(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            
            {% if form.content.errors %}
                {{ form.content(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.content(class="form-control") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
{% endblock %}

flaskypost/templates/password_reset_token.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="signup d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" style="width: 500px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">Password Reset</legend>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            
            {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.password(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.confirmPassword.label(class="form-control-label") }}
            
            {% if form.confirmPassword.errors %}
                {{ form.confirmPassword(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirmPassword.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.confirmPassword(class="form-control") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
{% endblock %}

flaskypost/templates/post.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="post d-flex flex-column justify-content-between">
    {% if post.author == current_user %}
        <div class="up-del">
            <a class="btn btn-secondary m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
    {% endif %}
    <div class="post-header">
        <div class="d-flex justify-content-center"><img class="rounded-circle account-img-post" src="{{ url_for('static', filename='profile_images/' + post.author.image) }}"></div>
        <h2 class="text-secondary" style="text-align: center; font-size: 20px;">Owner: <a class="text-secondary font-weight-bold" href="{{ url_for('users.user', username=post.author.username) }}">{{ post.author.username }}</a></h2>
    </div>
    <div class="post-content">
        <h1 class="display-4 mb-4 article-title" style="text-align: center;">{{ post.title }}</h1>
        <hr>
        <p style="text-align: center;" class="post-content-p">{{ post.content }}</p>
    </div>
    <p style="margin-top: 40px; font-size: 35px; opacity: 0.8;">- {{ post.date_posted.date() }} | {{ post.date_posted.strftime("%H") }}:{{ post.date_posted.strftime("%M") }}</p>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Post will be deleted forever!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input type="submit" class="btn btn-danger" value="Yes, I understand the consequences">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flaskypost/templates/profile.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p style="color: #FFC107;">{{ current_user.email }}</p>
    </div>
  </div>
  <div class="d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" enctype="multipart/form-data" style="width: 400px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">Profile Data</legend>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
                {{ form.username(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.username(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.email(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image.label() }}
            {{ form.image(class="form-control-file") }}
            {% if form.image.errors %}
                {% for error in form.image.errors %}<br>
                    <span class="text-danger">
                        {{ error }}
                    </span>
                {% endfor %}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
</div>
{% endblock %}

flaskypost/templates/resetPassword.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="signup d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" style="width: 500px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">Password Reset</legend>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.email(class="form-control") }}
            {% endif %}
        </div> 
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
{% endblock %}

flaskypost/templates/signup.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="signup d-flex justify-content-center" style="width: 500px; margin: auto;">
    <form action="" method="POST" style="width: 500px;">
    {{ form.hidden_tag() }}
    <fieldset class="form-group" style="color: #FFF;">
        <legend class="border-bottom mb-4 pb-2 text-center">Sign Up</legend>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
                {{ form.username(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.username(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            
            {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.email(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            
            {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.password(class="form-control") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.confirmPassword.label(class="form-control-label") }}
            
            {% if form.confirmPassword.errors %}
                {{ form.confirmPassword(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirmPassword.errors %}
                        <span>
                            {{ error }}
                        </span>
                    {% endfor %}
                </div>
            {% else %}
            {{ form.confirmPassword(class="form-control") }}
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group d-flex justify-content-center">
        {{ form.submit(class="btn btn-outline-warning") }}
    </div>
    </form>
</div>
<div style="width: 550px; margin: auto;">
    <small class="text-muted">
       <span style="color: #FFF;">Already Here?</span> <a href="{{ url_for('users.login') }}" class="ml-2" style="color: #FFC118;">Log In</a> 
    </small>
</div>
{% endblock %}

flaskypost/templates/user_page.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div class="content-section">
  <div class="media d-flex flex-column justify-content-center" style="margin-bottom: 90px;">
    <img class="rounded-circle account-img mb-3" src="{{ url_for('static', filename='profile_images/' + user.image) }}" style="margin: auto;">
    <div style="margin: auto;">
      <h2 class="account-heading" style="font-size: 20px; text-align: center;">{{ user.username }}</h2>
      <p style="color: #FFC107; font-size: 25px; text-align: center;">{{ user.email }}</p>
    </div>
  </div>

    {% for post in posts.items %}
    <div class="post d-flex flex-column justify-content-between">
        <div class="post-header">
        - {{ post.date_posted.date() }} | {{ post.date_posted.strftime("%H") }}:{{ post.date_posted.strftime("%M") }}
        </div>
        <div class="post-content">
            <h1 class="display-4 mb-4" style="text-align: center;"><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title" style="color: black;">{{ post.title[0:60] }}</a></h1>
            <hr>
            <p style="text-align: center;" class="post-content-p">{{ post.content[0:33] }}...</p>
        </div>
    </div>
    {% endfor %}
    <div class="page-nums d-flex justify-content-center" style="width: 330px; margin: auto;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-outline-secondary mb-4 ml-1" href="{{ url_for('users.user', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-secondary mb-4 ml-1" href="{{ url_for('users.user', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                <p class="btn ml-1" style="color: #fff;">...</p>
            {% endif %}
        {% endfor %}
    </div>

</div>
{% endblock %}